// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTolpi struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	UserID    string `json:"userId"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type Tolpi struct {
	ID        string `json:"_id"`
	Text      string `json:"text"`
	Timestamp int    `json:"timestamp"`
	User      *User  `json:"user"`
}

type User struct {
	ID        string `json:"_id"`
	UserID    string `json:"userId"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}
