// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTolpi struct {
	Text    string `json:"text"`
	Country string `json:"country"`
}

type NewUser struct {
	Avatar    string `json:"avatar"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type Tolpi struct {
	ID        string `json:"_id"`
	Text      string `json:"text"`
	Timestamp int    `json:"timestamp"`
	User      *User  `json:"user"`
	Country   string `json:"country"`
}

type User struct {
	ID          string   `json:"_id"`
	Avatar      string   `json:"avatar"`
	UserID      string   `json:"userId"`
	FirstName   string   `json:"firstName"`
	LastName    string   `json:"lastName"`
	Country     *string  `json:"country,omitempty"`
	TrackerList []string `json:"trackerList,omitempty"`
}
